
# all of your evolution scripts, mapping the from_version and to_version to a list if sql commands
sqlite3_evolutions = [
    [('fv1:350446761','fv1:710386236'), # generated 2008-01-14 13:20:20.870928
        "CREATE TABLE \"gPapers_publisher\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"name\" varchar(1024) NOT NULL,\n    \"created\" datetime NOT NULL,\n    \"updated\" datetime NOT NULL\n)\n;",
        "CREATE TABLE \"gPapers_playlist\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"title\" varchar(1024) NOT NULL,\n    \"search_text\" varchar(1024) NOT NULL,\n    \"parent\" varchar(1) NOT NULL,\n    \"created\" datetime NOT NULL,\n    \"updated\" datetime NOT NULL\n)\n;",
        "CREATE TABLE \"gPapers_reference\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"referencing_paper_id\" integer NULL,\n    \"referenced_paper_id\" integer NULL,\n    \"line_from_referencing_paper\" varchar(1024) NOT NULL,\n    \"line_from_referenced_paper\" varchar(1024) NOT NULL,\n    \"doi_from_referencing_paper\" varchar(1024) NOT NULL,\n    \"doi_from_referenced_paper\" varchar(1024) NOT NULL,\n    \"url_from_referencing_paper\" varchar(200) NOT NULL,\n    \"url_from_referenced_paper\" varchar(200) NOT NULL,\n    \"created\" datetime NOT NULL,\n    \"updated\" datetime NOT NULL\n)\n;",
        "CREATE TABLE \"gPapers_author\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"name\" varchar(1024) NOT NULL,\n    \"location\" varchar(1024) NOT NULL,\n    \"department\" varchar(1024) NOT NULL,\n    \"created\" datetime NOT NULL,\n    \"updated\" datetime NOT NULL\n)\n;",
        "CREATE TABLE \"gPapers_bookmark\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"paper_id\" integer NOT NULL,\n    \"page\" integer NOT NULL,\n    \"notes\" text NOT NULL,\n    \"created\" datetime NOT NULL,\n    \"updated\" datetime NOT NULL\n)\n;",
        "CREATE TABLE \"gPapers_source\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"name\" varchar(1024) NOT NULL,\n    \"issue\" varchar(1024) NOT NULL,\n    \"acm_toc_url\" varchar(200) NOT NULL,\n    \"location\" varchar(1024) NOT NULL,\n    \"publication_date\" date NULL,\n    \"publisher_id\" integer NULL REFERENCES \"gPapers_publisher\" (\"id\"),\n    \"created\" datetime NOT NULL,\n    \"updated\" datetime NOT NULL\n)\n;",
        "CREATE TABLE \"gPapers_paper\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"title\" varchar(1024) NOT NULL,\n    \"doi\" varchar(1024) NOT NULL,\n    \"source_id\" integer NULL REFERENCES \"gPapers_source\" (\"id\"),\n    \"source_session\" varchar(1024) NOT NULL,\n    \"source_pages\" varchar(1024) NOT NULL,\n    \"abstract\" text NOT NULL,\n    \"notes\" text NOT NULL,\n    \"full_text\" varchar(100) NOT NULL,\n    \"rating\" integer NOT NULL,\n    \"created\" datetime NOT NULL,\n    \"updated\" datetime NOT NULL\n)\n;",
        "CREATE TABLE \"gPapers_sponsor\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"name\" varchar(1024) NOT NULL,\n    \"created\" datetime NOT NULL,\n    \"updated\" datetime NOT NULL\n)\n;",
        "CREATE TABLE \"gPapers_organization\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"name\" varchar(1024) NOT NULL,\n    \"location\" varchar(1024) NOT NULL,\n    \"created\" datetime NOT NULL,\n    \"updated\" datetime NOT NULL\n)\n;",
        "CREATE TABLE \"gPapers_playlist_papers\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"playlist_id\" integer NOT NULL REFERENCES \"gPapers_playlist\" (\"id\"),\n    \"paper_id\" integer NOT NULL REFERENCES \"gPapers_paper\" (\"id\"),\n    UNIQUE (\"playlist_id\", \"paper_id\")\n)\n;",
        "CREATE TABLE \"gPapers_author_organizations\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"author_id\" integer NOT NULL REFERENCES \"gPapers_author\" (\"id\"),\n    \"organization_id\" integer NOT NULL REFERENCES \"gPapers_organization\" (\"id\"),\n    UNIQUE (\"author_id\", \"organization_id\")\n)\n;",
        "CREATE TABLE \"gPapers_paper_authors\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"paper_id\" integer NOT NULL REFERENCES \"gPapers_paper\" (\"id\"),\n    \"author_id\" integer NOT NULL REFERENCES \"gPapers_author\" (\"id\"),\n    UNIQUE (\"paper_id\", \"author_id\")\n)\n;",
        "CREATE TABLE \"gPapers_paper_sponsors\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"paper_id\" integer NOT NULL REFERENCES \"gPapers_paper\" (\"id\"),\n    \"sponsor_id\" integer NOT NULL REFERENCES \"gPapers_sponsor\" (\"id\"),\n    UNIQUE (\"paper_id\", \"sponsor_id\")\n)\n;",
        "CREATE TABLE \"gPapers_paper_organizations\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"paper_id\" integer NOT NULL REFERENCES \"gPapers_paper\" (\"id\"),\n    \"organization_id\" integer NOT NULL REFERENCES \"gPapers_organization\" (\"id\"),\n    UNIQUE (\"paper_id\", \"organization_id\")\n)\n;",
    ],
    [('fv1:710386236','fv1:-601791475'), # generated 2008-01-15 19:03:43.467515
        "ALTER TABLE \"gPapers_paper\" ADD COLUMN \"full_text_md5\" varchar(32) NULL;",
        "UPDATE \"gPapers_paper\" SET \"full_text_md5\" = '' WHERE \"full_text_md5\" IS NULL ;",
        "-- FYI: sqlite does not support changing columns, so we create a new \"gPapers_paper\" and delete the old (ie, this could take a while if you have a lot of data)",
        "ALTER TABLE \"gPapers_paper\" RENAME TO \"gPapers_paper_1337_TMP\";",
        "CREATE TABLE \"gPapers_paper\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"title\" varchar(1024) NOT NULL,\n    \"doi\" varchar(1024) NOT NULL,\n    \"source_id\" integer NULL REFERENCES \"gPapers_source\" (\"id\"),\n    \"source_session\" varchar(1024) NOT NULL,\n    \"source_pages\" varchar(1024) NOT NULL,\n    \"abstract\" text NOT NULL,\n    \"notes\" text NOT NULL,\n    \"full_text\" varchar(100) NOT NULL,\n    \"full_text_md5\" varchar(32) NOT NULL,\n    \"rating\" integer NOT NULL,\n    \"created\" datetime NOT NULL,\n    \"updated\" datetime NOT NULL\n)\n;",
        "INSERT INTO \"gPapers_paper\" SELECT \"id\",\"title\",\"doi\",\"source_id\",\"source_session\",\"source_pages\",\"abstract\",\"notes\",\"full_text\",\"full_text_md5\",\"rating\",\"created\",\"updated\" FROM \"gPapers_paper_1337_TMP\";",
        "DROP TABLE \"gPapers_paper_1337_TMP\";",
    ],
    [('fv1:-601791475','fv1:973383202'), # generated 2008-01-18 17:07:22.335450
        "ALTER TABLE \"gPapers_paper\" ADD COLUMN \"read_count\" integer NULL;",
        "UPDATE \"gPapers_paper\" SET \"read_count\" = 0 WHERE \"read_count\" IS NULL ;",
        "-- FYI: sqlite does not support changing columns, so we create a new \"gPapers_paper\" and delete the old (ie, this could take a while if you have a lot of data)",
        "ALTER TABLE \"gPapers_paper\" RENAME TO \"gPapers_paper_1337_TMP\";",
        "CREATE TABLE \"gPapers_paper\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"title\" varchar(1024) NOT NULL,\n    \"doi\" varchar(1024) NOT NULL,\n    \"source_id\" integer NULL REFERENCES \"gPapers_source\" (\"id\"),\n    \"source_session\" varchar(1024) NOT NULL,\n    \"source_pages\" varchar(1024) NOT NULL,\n    \"abstract\" text NOT NULL,\n    \"notes\" text NOT NULL,\n    \"full_text\" varchar(100) NOT NULL,\n    \"full_text_md5\" varchar(32) NOT NULL,\n    \"rating\" integer NOT NULL,\n    \"read_count\" integer NOT NULL,\n    \"created\" datetime NOT NULL,\n    \"updated\" datetime NOT NULL\n)\n;",
        "INSERT INTO \"gPapers_paper\" SELECT \"id\",\"title\",\"doi\",\"source_id\",\"source_session\",\"source_pages\",\"abstract\",\"notes\",\"full_text\",\"full_text_md5\",\"rating\",\"read_count\",\"created\",\"updated\" FROM \"gPapers_paper_1337_TMP\";",
        "DROP TABLE \"gPapers_paper_1337_TMP\";",
    ],
    [('fv1:973383202','fv1:1245036263'), # generated 2008-01-22 18:17:43.604272
        "ALTER TABLE \"gPapers_paper\" ADD COLUMN \"bibtex\" text NULL;",
        "UPDATE \"gPapers_paper\" SET \"bibtex\" = '' WHERE \"bibtex\" IS NULL ;",
        "-- FYI: sqlite does not support changing columns, so we create a new \"gPapers_paper\" and delete the old (ie, this could take a while if you have a lot of data)",
        "ALTER TABLE \"gPapers_paper\" RENAME TO \"gPapers_paper_1337_TMP\";",
        "CREATE TABLE \"gPapers_paper\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"title\" varchar(1024) NOT NULL,\n    \"doi\" varchar(1024) NOT NULL,\n    \"source_id\" integer NULL REFERENCES \"gPapers_source\" (\"id\"),\n    \"source_session\" varchar(1024) NOT NULL,\n    \"source_pages\" varchar(1024) NOT NULL,\n    \"abstract\" text NOT NULL,\n    \"notes\" text NOT NULL,\n    \"full_text\" varchar(100) NOT NULL,\n    \"full_text_md5\" varchar(32) NOT NULL,\n    \"rating\" integer NOT NULL,\n    \"read_count\" integer NOT NULL,\n    \"bibtex\" text NOT NULL,\n    \"created\" datetime NOT NULL,\n    \"updated\" datetime NOT NULL\n)\n;",
        "INSERT INTO \"gPapers_paper\" SELECT \"id\",\"title\",\"doi\",\"source_id\",\"source_session\",\"source_pages\",\"abstract\",\"notes\",\"full_text\",\"full_text_md5\",\"rating\",\"read_count\",\"bibtex\",\"created\",\"updated\" FROM \"gPapers_paper_1337_TMP\";",
        "DROP TABLE \"gPapers_paper_1337_TMP\";",
    ],
    [('fv1:1245036263','fv1:-1992981100'), # generated 2008-01-30 12:19:58.507907
        "ALTER TABLE \"gPapers_paper\" ADD COLUMN \"extracted_text\" text NULL;",
        "UPDATE \"gPapers_paper\" SET \"extracted_text\" = '' WHERE \"extracted_text\" IS NULL ;",
        "-- FYI: sqlite does not support changing columns, so we create a new \"gPapers_paper\" and delete the old (ie, this could take a while if you have a lot of data)",
        "ALTER TABLE \"gPapers_paper\" RENAME TO \"gPapers_paper_1337_TMP\";",
        "CREATE TABLE \"gPapers_paper\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"title\" varchar(1024) NOT NULL,\n    \"doi\" varchar(1024) NOT NULL,\n    \"source_id\" integer NULL REFERENCES \"gPapers_source\" (\"id\"),\n    \"source_session\" varchar(1024) NOT NULL,\n    \"source_pages\" varchar(1024) NOT NULL,\n    \"abstract\" text NOT NULL,\n    \"notes\" text NOT NULL,\n    \"full_text\" varchar(100) NOT NULL,\n    \"full_text_md5\" varchar(32) NOT NULL,\n    \"extracted_text\" text NOT NULL,\n    \"rating\" integer NOT NULL,\n    \"read_count\" integer NOT NULL,\n    \"bibtex\" text NOT NULL,\n    \"created\" datetime NOT NULL,\n    \"updated\" datetime NOT NULL\n)\n;",
        "INSERT INTO \"gPapers_paper\" SELECT \"id\",\"title\",\"doi\",\"source_id\",\"source_session\",\"source_pages\",\"abstract\",\"notes\",\"full_text\",\"full_text_md5\",\"extracted_text\",\"rating\",\"read_count\",\"bibtex\",\"created\",\"updated\" FROM \"gPapers_paper_1337_TMP\";",
        "DROP TABLE \"gPapers_paper_1337_TMP\";",
    ],
    [('fv1:-1992981100','fv1:-2070349988'), # generated 2008-01-30 12:32:02.047776
        "ALTER TABLE \"gPapers_paper\" ADD COLUMN \"page_count\" integer NULL;",
        "UPDATE \"gPapers_paper\" SET \"page_count\" = 0 WHERE \"page_count\" IS NULL ;",
        "-- FYI: sqlite does not support changing columns, so we create a new \"gPapers_paper\" and delete the old (ie, this could take a while if you have a lot of data)",
        "ALTER TABLE \"gPapers_paper\" RENAME TO \"gPapers_paper_1337_TMP\";",
        "CREATE TABLE \"gPapers_paper\" (\n    \"id\" integer NOT NULL PRIMARY KEY,\n    \"title\" varchar(1024) NOT NULL,\n    \"doi\" varchar(1024) NOT NULL,\n    \"source_id\" integer NULL REFERENCES \"gPapers_source\" (\"id\"),\n    \"source_session\" varchar(1024) NOT NULL,\n    \"source_pages\" varchar(1024) NOT NULL,\n    \"abstract\" text NOT NULL,\n    \"notes\" text NOT NULL,\n    \"full_text\" varchar(100) NOT NULL,\n    \"full_text_md5\" varchar(32) NOT NULL,\n    \"extracted_text\" text NOT NULL,\n    \"page_count\" integer NOT NULL,\n    \"rating\" integer NOT NULL,\n    \"read_count\" integer NOT NULL,\n    \"bibtex\" text NOT NULL,\n    \"created\" datetime NOT NULL,\n    \"updated\" datetime NOT NULL\n)\n;",
        "INSERT INTO \"gPapers_paper\" SELECT \"id\",\"title\",\"doi\",\"source_id\",\"source_session\",\"source_pages\",\"abstract\",\"notes\",\"full_text\",\"full_text_md5\",\"extracted_text\",\"page_count\",\"rating\",\"read_count\",\"bibtex\",\"created\",\"updated\" FROM \"gPapers_paper_1337_TMP\";",
        "DROP TABLE \"gPapers_paper_1337_TMP\";",
    ],
] # don't delete this comment! ## sqlite3_evolutions_end ##
